package com.demo.entities;
// Generated Feb 26, 2024, 1:59:46 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", catalog = "booking_hotel")
public class Area implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Hotel> hotels = new HashSet<Hotel>(0);

	public Area() {
	}

	public Area(String name, Set<Hotel> hotels) {
		this.name = name;
		this.hotels = hotels;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Hotel> getHotels() {
		return this.hotels;
	}

	public void setHotels(Set<Hotel> hotels) {
		this.hotels = hotels;
	}

}
