package com.demo.entities;
// Generated Mar 14, 2024, 4:13:24 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * BookRoom generated by hbm2java
 */
@Entity
@Table(name = "book_room", catalog = "booking_hotel")
public class BookRoom implements java.io.Serializable {

	private Integer id;
	private Book book;
	private DatePrice datePrice;
	@DateTimeFormat(pattern = "dd-MM-yyyy")
	private Date created;
	@DateTimeFormat(pattern = "dd-MM-yyyy")
	private Date updated;
	private Double price;
	private Integer quantity;

	public BookRoom() {
	}

	public BookRoom(Book book, DatePrice datePrice) {
		this.book = book;
		this.datePrice = datePrice;
	}

	public BookRoom(Book book, DatePrice datePrice, Date created, Date updated, Double price, Integer quantity) {
		this.book = book;
		this.datePrice = datePrice;
		this.created = created;
		this.updated = updated;
		this.price = price;
		this.quantity = quantity;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_id", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "date_id", nullable = false)
	public DatePrice getDatePrice() {
		return this.datePrice;
	}

	public void setDatePrice(DatePrice datePrice) {
		this.datePrice = datePrice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated", length = 10)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
