package com.demo.entities;
// Generated Mar 14, 2024, 4:13:24 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "booking_hotel")
public class Book implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String codeBook;
	private double total;
	private Date date;
	private String note;
	private boolean status;
	@DateTimeFormat(pattern = "dd-MM-yyyy")
	private Date created;
	@DateTimeFormat(pattern = "dd-MM-yyyy")
	private Date updated;
	private Set<BookRoom> bookRooms = new HashSet<BookRoom>(0);

	public Book() {
	}

	public Book(Account account, String codeBook, double total, Date date, boolean status) {
		this.account = account;
		this.codeBook = codeBook;
		this.total = total;
		this.date = date;
		this.status = status;
	}

	public Book(Account account, String codeBook, double total, Date date, String note, boolean status, Date created,
			Date updated, Set<BookRoom> bookRooms) {
		this.account = account;
		this.codeBook = codeBook;
		this.total = total;
		this.date = date;
		this.note = note;
		this.status = status;
		this.created = created;
		this.updated = updated;
		this.bookRooms = bookRooms;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "code_book", nullable = false, length = 250)
	public String getCodeBook() {
		return this.codeBook;
	}

	public void setCodeBook(String codeBook) {
		this.codeBook = codeBook;
	}

	@Column(name = "total", nullable = false, precision = 22, scale = 0)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "note", length = 250)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated", length = 10)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookRoom> getBookRooms() {
		return this.bookRooms;
	}

	public void setBookRooms(Set<BookRoom> bookRooms) {
		this.bookRooms = bookRooms;
	}

}
