package com.demo.entities;
// Generated Feb 26, 2024, 1:59:46 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * Evaluate generated by hbm2java
 */
@Entity
@Table(name = "evaluate", catalog = "booking_hotel")
public class Evaluate implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Hotel hotel;
	private String content;
	private Integer star;
	private Boolean status;

	public Evaluate() {
	}

	public Evaluate(Account account, Hotel hotel) {
		this.account = account;
		this.hotel = hotel;
	}

	public Evaluate(Account account, Hotel hotel, String content, Integer star, Boolean status) {
		this.account = account;
		this.hotel = hotel;
		this.content = content;
		this.star = star;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotel_id", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "content", length = 250)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "star")
	public Integer getStar() {
		return this.star;
	}

	public void setStar(Integer star) {
		this.star = star;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
