package com.demo.entities;
// Generated Mar 14, 2024, 4:13:24 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", catalog = "booking_hotel")
public class Room implements java.io.Serializable {

	private Integer id;
	private Hotel hotel;
	private String content;
	private Integer fixedQuantity;
	@DateTimeFormat(pattern = "dd-MM-yyyy")
	private Date created;
	@DateTimeFormat(pattern = "dd-MM-yyyy")
	private Date updated;
	private Set<Image> images = new HashSet<Image>(0);
	private Set<Kindofroom> kindofrooms = new HashSet<Kindofroom>(0);
	private Set<DatePrice> datePrices = new HashSet<DatePrice>(0);
	private Integer status;

	public Room() {
	}

	public Room(Hotel hotel) {
		this.hotel = hotel;
	}

	public Room(Hotel hotel, String content, Integer fixedQuantity, Date created, Date updated, Set<Image> images,
			Set<Kindofroom> kindofrooms, Set<DatePrice> datePrices, Integer status) {
		this.hotel = hotel;
		this.content = content;
		this.fixedQuantity = fixedQuantity;
		this.created = created;
		this.updated = updated;
		this.images = images;
		this.kindofrooms = kindofrooms;
		this.datePrices = datePrices;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotel_id", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "content", length = 250)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "fixed_quantity")
	public Integer getFixedQuantity() {
		return this.fixedQuantity;
	}

	public void setFixedQuantity(Integer fixedQuantity) {
		this.fixedQuantity = fixedQuantity;
	}
	
	
	@Column(name = "status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated", length = 10)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<Kindofroom> getKindofrooms() {
		return this.kindofrooms;
	}

	public void setKindofrooms(Set<Kindofroom> kindofrooms) {
		this.kindofrooms = kindofrooms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<DatePrice> getDatePrices() {
		return this.datePrices;
	}

	public void setDatePrices(Set<DatePrice> datePrices) {
		this.datePrices = datePrices;
	}

}
